version: '3.8'

networks:
  bridged_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bridged_network

  mongodb-data-fetcher:
    image: mongo:latest
    container_name: mongodb-data-fetcher
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb-data-fetcher:/data/db
    networks:
      - bridged_network

  data-fetcher:
    build:
      context: src/microservices/data-fetcher
      dockerfile: Dockerfile
    container_name: data-fetcher
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672"
      RABBITMQ_QUEUE: "f1.data.fetcher"
      MONGO_URL: "mongodb://mongodb-data-fetcher:27017"
    networks:
      - bridged_network
    depends_on:
      - rabbitmq
      - mongodb-data-fetcher

  mongodb-race-simulator:
    image: mongo:latest
    container_name: mongodb-race-simulator
    ports:
      - "27018:27017"
    volumes:
      - /var/lib/mongodb-race-simulator:/data/db
    networks:
      - bridged_network

  race-simulator:
    build:
      context: src/microservices/race-simulator
      dockerfile: Dockerfile
    container_name: race-simulator
    ports:
      - "8002:8002"
    environment:
      MONGO_URL: "mongodb://mongodb-race-simulator:27017"
    networks:
      - bridged_network
    depends_on:
      - mongodb-race-simulator

  mongodb-user-service:
    image: mongo:latest
    container_name: mongodb-user-service
    ports:
      - "27019:27017"
    volumes:
      - /var/lib/mongodb-user-service:/data/db
    networks:
      - bridged_network

  user-service:
    build:
      context: src/microservices/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: "mongodb://mongodb-user-service:27017"
      DATA_FETCHER_URL: "http://data-fetcher:8000"
      SECRET_KEY: "secret_key"
    networks:
      - bridged_network
    depends_on:
      - mongodb-user-service

  mongodb-predictions-service:
    image: mongo:latest
    container_name: mongodb-predictions-service
    ports:
      - "27020:27017"
    volumes:
      - /var/lib/mongodb-predictions-service:/data/db
    networks:
      - bridged_network

  predictions-service:
    build:
      context: src/microservices/predictions-service
      dockerfile: Dockerfile
    container_name: predictions-service
    ports:
      - "8004:8004"
    environment:
      MONGO_URL: "mongodb://mongodb-predictions-service:27017"
      SECRET_KEY: "secret_key"
    networks:
      - bridged_network
    depends_on:
      - mongodb-predictions-service

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    depends_on:
      - race-simulator
      - data-fetcher
      - user-service
      - predictions-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bridged_network