apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  labels:
    app: data-fetcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-fetcher
  template:
    metadata:
      name: data-fetcher
      labels:
        app: data-fetcher
    spec:
      containers:
        - name: data-fetcher
          image: tr0yyy/f1-prediction-python-data-fetcher
          ports:
              - containerPort: 8000
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:password@rabbitmq:5672"
            - name: MONGO_URL
              value: "mongodb://mongodb-data-fetcher:27017"
            - name: PORT
              value: "8000"
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
